apiVersion: v1
kind: Secret
metadata:
  name: wechat
  namespace: srv
data:
  miniprogram-app-id: TFRBSWRzS1RrbXpySVY1Uw==
  miniprogram-secret: aHNXRlhYTzdpWnlzcktWSnRvTXp5UmFhRU5RYzJ3
---
kind: Service
apiVersion: v1
metadata:
  name: wechat
  namespace: srv
spec:
  selector:
    app: wechat
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      name: micro
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wechat
  namespace: srv
  labels:
    app: wechat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wechat
  template:
    metadata:
      labels:
        app: wechat
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
        - name: wechat
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          imagePullPolicy: Always
          command: [
            "service",
            "--selector=static",
            "--server_address=:8080",
          ]
          env:
            - name: MINIPROGRAM_APP_ID
              valueFrom:
                secretKeyRef:
                  key: miniprogram-app-id
                  name: wechat
            - name: MINIPROGRAM_SECRET
              valueFrom:
                secretKeyRef:
                  key: miniprogram-secret
                  name: wechat
          ports:
          - containerPort: 8080
            name: micro
            protocol: TCP
        - name: health
          image: microhq/health:kubernetes
          command: [
            "/health",
            "--health_address=0.0.0.0:8081",
            "--server_name=wechat",
            "--server_address=0.0.0.0:8080"
          ]
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3
